### ISSUE TITLE
1. Criar tela inicial do aplicativo

### ISSUE THREAD

**Issue by jorgejunior618** [jorgejunior618/hackathon_gov_ce#3]
Subtasks:
- [x] Criar Barra de Navegação inferior (navegar entre as duas telas de início - Notícias e Gastos);
- [x] Criar tela "Noticias" preenchida com dados genéricos;
- [x] Criar tela de Menu para amostragem dos dados.

**Comment by JardelBrasiliano** [comment]
feito
